apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mi-aplicacion
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/usuario/mi-repo.git'
    targetRevision: HEAD
    path: carpeta/de/la/aplicacion
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mi-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
#Explicación de los Campos:
apiVersion y kind: Indican que se trata de un recurso Application de Argo CD.

metadata: Contiene el nombre y el espacio de nombres del recurso.

spec: Especifica los detalles de la aplicación que Argo CD gestionará.

project: El proyecto al que pertenece la aplicación en Argo CD (por defecto, default).

source: Define la fuente de la aplicación.

repoURL: URL del repositorio Git donde se encuentra el código.
targetRevision: La rama, etiqueta o commit específico (por ejemplo, HEAD, main, v1.0.0).
path: La ruta dentro del repositorio donde se encuentran los archivos de configuración.
destination: Define dónde desplegar la aplicación.

server: La dirección del servidor de Kubernetes (por defecto, el clúster actual).
namespace: El espacio de nombres de Kubernetes donde se desplegará la aplicación.
syncPolicy: Define la política de sincronización.

automated: Habilita la sincronización automática.

prune: Elimina los recursos que ya no están en el repositorio.
selfHeal: Corrige automáticamente las desviaciones entre el estado deseado y el actual.
