apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mi-aplicacion
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/usuario/mi-repo.git'
    targetRevision: HEAD
    path: carpeta/de/la/aplicacion
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mi-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
