---
apiVersion: v1
kind: Secret
metadata:
  name: argo-events-demo-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
data:
  name: YXJnby1ldmVudHMtZGVtbw==  # Nombre del contexto del clúster en base64 (argo-events-demo)
  server: aHR0cHM6Ly8xOTIuMTY4LjY3LjI6ODQ0Mw==  # Dirección del API Server en base64 (https://192.168.67.2:8443)
  config: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Fo
    a2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJME1UQXdN
    VEU1TVRReU1Wb1hEVE0wTURrek1ERTVNVFF5TVZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZ
    bVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT2Q1CjdHUk1r
    azhhSmJwOFVBcnlmbHFVT2JVTDQ5NE9QLy9MSlhvNnU3TGhIL1NGLzBnZkxTazVCVWN3dlo2Q29l
    Q04KUGM5ZDRpNGtEZ2dwVC9SRkZhcW5nb1FvT1ViSndBYVlQNmM1d1V4MkJFaGMzNjNidlRUNjJq
    dmFhMXFqeGhTMAppWlB6MTJRZmRYMUtCb2k0eVdRSUdGNGkrNjFTeFJYcGVDc1NibXlKVXpVeEZL
    K25xSkY2cjNTU2hBc0lFTFRlCm1kVmlEa2hjM3ZkSGNLc1Y4WFNTNjRXc1BKTmNiVW9NQ2VacmQ5
    WktNeUpDWTNRdDZENndBTVJ6aWdvRWhOV2oKemF0VDRXSkhPSmhUNDFsblBITEsvR3BsSHF1aWUr
    cS8xTVpLYzQwNytEOS9QcHlHSXYxMUtZcG5kd2JkSTREOAphQlBMa1B2S284Uzh1TGlPRkZVQ0F3
    RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3
    TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJTMXNx
    azhoZkt3K1RiTklLUnRhczdPdVBySzFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFWaEUxNXQr
    cgpab3FONHVWeUlnbjQyM1pYTUVaWW4ydk5YOC9lUjFyZFZVMjIvMVdVU2pEOCtESHZrZzJSeG9i
    Vm5TN2NiS2VXClV1cFpIYlJyODMwQSttb3FuR2ltVnA1R3FsTldybUlWNm9NanBIME9rRm11aEpi
    aC85VmpOSTJidWJhTWg5a2MKMWg5ck9UVFlHdWhwQVRMU01sRXZqSkF0WkdqS3RSZ29sVW80L1h3
    a0RaYjVrVytIOE5MVTdCY2YzUXRZN1RHaQpTQ0F5MmE1S1VhRW9nRDZZdWthSmU2TDlxc2dpcHE3
    eFZvMzZ5aGgwRXdHRXpscjlVR0NOYy80YkRsM0Q2d04wClF4QzRvMXlYR3I4TncyQVh2M2lKa3lU
    M0FRWUh3SmxBcTNxd3pYMnREUFlFVDM0dk1XNDRuUS9wa2pRbDJ2SmIKbXRQaHVoWDlTMENJbEE9
    PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==



---------------------------------------------------
echo -n "argo-events-demo" | base64   Para codificar el nombre del cluster en base64
echo -n "https://192.168.67.2:8443" | base64  Para codificar la direccion ip

