apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: cron-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: test-cron-event
      eventSourceName: cron-event-source
      eventName: example   # El nombre del Evento es el nombre que tenemos en el archivo-cron-event-source.yaml
  triggers:
    - template:
        name: log-trigger
        conditions: "deps.test-cron-event"
        k8s:
          group: ""
          version: v1
          resource: Pod
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: log-pod-
                namespace: argo-events
              spec:
                containers:
                  - name: log-container
                    image: alpine
                    command: ["/bin/sh", "-c"]
                    args: ["echo 'Event detected from Cron!'; sleep 300"]
                restartPolicy: Never

# Componentes y Configuraciones
Explicación línea por línea:
apiVersion: argoproj.io/v1alpha1: Versión de la API de Argo Events utilizada para definir el recurso.
kind: EventSource: Tipo de recurso. Este archivo define una fuente de eventos.
metadata:: Información de metadatos del recurso.
name: cron-event-source: Nombre del EventSource. Se usará para identificar la fuente de evento.
namespace: argo-events: Namespace donde este recurso existirá dentro de Kubernetes.
spec:: Especifica los detalles de la fuente de evento.
template:: Plantilla para el despliegue del EventSource.
serviceAccountName: argo-events-sa: El EventSource utilizará una cuenta de servicio llamada argo-events-sa para acceder a los recursos del clúster.
cron:: Define un cron job como la fuente del evento.
example:: Nombre del evento dentro del EventSource.
schedule: "*/5 * * * *": El cron job se ejecutará cada 5 minutos. El formato utilizado aquí es similar a la sintaxis crontab.
timezone: "UTC": Establece la zona horaria en UTC.
payload: '{"message": "Hello from Cron EventSource!"}': Contenido que se enviará cuando se dispare el evento. Este payload puede ser utilizado por el componente que reciba el evento.
eventBusName: default: Nombre del EventBus al cual se enviarán los eventos. default es el EventBus que se configura por defecto en Argo Events.
