apiVersion: v1
kind: Service
metadata:
  name: github-event-source-svc
  namespace: argo-events
spec:
  selector:
    app: github-event-source
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
