apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-event-source
  namespace: argo-events
spec:
  githubs:
    - name: example
      owner: pick-ia
      repository: argocd-demo
      events:
        - push
      apiToken:
        valueFrom:
          secretKeyRef:
            name: github-access  # es el nombre del secreto en Kubernetes
            key: token   # el token que hemos generado en GitHub
      webhook:
        port: "12000"
