apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: log-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: every-minute
      eventSourceName: cron-event-source
      eventName: every-minute
  triggers:
    - template:
        name: log-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: log-workflow-
              spec:
                entrypoint: log-message
                templates:
                  - name: log-message
                    container:
                      image: alpine
                      command: [echo]
                      args: ["{{(payload)}}"]
