apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-event-source
  namespace: argo-events
spec:
  webhooks:
    - port: "12000"
      endpoint: /webhook
      method: POST
      name: example-webhook
