apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor  # Nombre del sensor.
  namespace: argo-events  # Namespace donde se desplegará este sensor.
spec:
  dependencies:
    - name: example-webhook  # Nombre de la dependencia que será utilizada en el sensor.
      eventSourceName: webhook-event-source  # Nombre de la fuente de evento definida en webhook-event-source.yaml.
      eventName: example-webhook  # Nombre del evento que debe coincidir con el nombre especificado en webhook-event-source.yaml.
  triggers:
    - template:
        name: webhook-trigger  # Nombre del disparador (trigger).
        argoWorkflow:
          group: argoproj.io  # Grupo al que pertenece el recurso en la API.
          version: v1alpha1  # Versión de la API utilizada para los workflows.
          resource: workflows  # Tipo de recurso que se activará; en este caso, un Workflow.
          operation: submit  # Operación que se realizará: envío de un workflow.
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1  # Versión de la API de Argo utilizada.
              kind: Workflow  # Tipo de recurso que se creará, en este caso, un Workflow.
              metadata:
                generateName: webhook-workflow-  # Prefijo del nombre generado automáticamente para el Workflow.
              spec:
                entrypoint: log-message  # Punto de entrada del Workflow.
                templates:
                  - name: log-message  # Nombre de la plantilla que será ejecutada.
                    container:
                      image: alpine  # Imagen utilizada para el contenedor.
                      command: [echo]  # Comando ejecutado en el contenedor.
                      args: ["{{(payload)}}"]  # Argumento que utilizará el payload recibido del webhook.

# El Sensor espera a que se reciba un evento example-webhook desde el EventSource webhook-event-source. 
#Cuando esto ocurre, el Sensor desencadena el trigger webhook-trigger, que envía (submits) un Workflow a Argo Workflows.
#El Workflow simplemente ejecuta un contenedor de Alpine que imprime el contenido del payload del evento usando el comando echo.
