apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-event-source
  namespace: argo-events
spec:
  webhooks:
    - port: "12000"
      endpoint: /webhook
      method: POST
      name: example-webhook
#----------------------------------

Explicación:

apiVersion y kind:

apiVersion: argoproj.io/v1alpha1: Versión de la API.
kind: EventSource: Especifica que este recurso es un EventSource.
metadata:

name: webhook-event-source: Nombre del EventSource.
namespace: argo-events: Espacio de nombres.
spec:

service:
ports:
port: 12000: Puerto en el que el servicio estará disponible.
targetPort: 12000: Puerto en el que el pod del EventSource está escuchando.
webhooks:
Es una lista de configuraciones de webhooks que el EventSource manejará.
- name: example-webhook: Nombre del webhook dentro del EventSource.
port: "12000": Puerto en el que el EventSource escucha para este webhook (como cadena de texto).
endpoint: /webhook: Ruta del endpoint donde el webhook recibirá las solicitudes HTTP.
method: POST: Método HTTP que el webhook aceptará.
Función:

Este EventSource configura un servidor HTTP que escucha en el puerto 12000 y en el endpoint /webhook para solicitudes POST. Cuando recibe una solicitud en esa ruta, genera un evento que puede ser consumido por un Sensor.
