apiVersion: v1
kind: Service
metadata:
  name: webhook-event-source-svc
  namespace: argo-events
spec:
  selector:
    eventsource-name: webhook-event-source
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
