apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-event-source
  namespace: argo-events
spec:
  webhooks:
    - port: "12000"
      endpoint: /webhook
      method: POST
      name: example-webhook
#----------------------------------

apiVersion: argoproj.io/v1alpha1: Versión de la API de Argo Events utilizada para definir el recurso.
kind: EventSource: Tipo de recurso. Este archivo define una fuente de eventos.
metadata:: Información de metadatos del recurso.
name: webhook-event-source: Nombre del EventSource que identificará esta fuente de evento.
namespace: argo-events: Namespace donde este recurso existirá en Kubernetes.
spec:: Define las especificaciones de la fuente de evento.
webhooks:: Define un webhook como la fuente del evento.
- port: "12000": Puerto en el cual el servidor estará escuchando solicitudes entrantes. Este webhook está configurado para escuchar en el puerto 12000.
endpoint: /webhook: Endpoint específico donde se recibirán las solicitudes HTTP. Aquí, el webhook escuchará en la ruta /webhook.
method: POST: Método HTTP aceptado por el endpoint; en este caso, solo se aceptan solicitudes de tipo POST.
name: example-webhook: Nombre del webhook que se utilizará para referenciarlo en otros recursos, como un sensor por ejemplo.

Este EventSource configura un servidor HTTP que escucha en el puerto 12000 y en el endpoint /webhook para solicitudes POST.
Cuando recibe una solicitud en esa ruta, genera un evento que puede ser consumido por un Sensor.
Este archivo define una fuente de evento (EventSource) basada en un webhook en Argo Events. Un webhook es un mecanismo que permite recibir notificaciones HTTP desde otras aplicaciones o servicios.
