apiVersion: v1
kind: Service
metadata:
  name: webhook-event-source-svc
  namespace: argo-events
spec:
  selector:
    eventsource-name: webhook-event-source
  ports:
    - protocol: TCP
      port: 12000
      targetPort: 12000
#----------------------------------
Explicación:

apiVersion y kind:

apiVersion: v1: Versión de la API de Kubernetes para servicios.
kind: Service: Especifica que este recurso es un Service.
metadata:

name: webhook-event-source-svc: Nombre del servicio.
namespace: argo-events: Espacio de nombres.
spec:

selector:
eventsource-name: webhook-event-source: Selecciona los pods que tienen la etiqueta eventsource-name=webhook-event-source.
ports:
protocol: TCP: Protocolo utilizado.
port: 12000: Puerto en el que el servicio estará disponible dentro del clúster.
targetPort: 12000: Puerto al que el servicio enviará el tráfico en los pods seleccionados.
Función:

El servicio permite acceder al EventSource desde fuera del pod. Como el EventSource está ejecutándose dentro del clúster, necesitamos un Service para dirigir el tráfico al pod correcto. Este servicio será utilizado para hacer port-forwarding y acceder al webhook desde nuestra máquina local.
